# Generated by Django 5.2.8 on 2025-11-26 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('category', models.CharField(choices=[('LUZ', 'Luz'), ('AGUA', 'Agua'), ('ALQUILER', 'Alquiler'), ('TRANSPORTE', 'Transporte'), ('PERSONAL', 'Personal'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
